name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

steps:
- template: build-package.netcore.yaml@templates