name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

steps:
- template: build-package.netcore.yaml@templates
  parameters:
    packagePath: |
      Audacia.Seed/Audacia.Seed.csproj
      Audacia.Seed.AutoFixture/Audacia.Seed.AutoFixture.csproj
      Audacia.Seed.EntityFrameworkCore/Audacia.Seed.EntityFrameworkCore.csproj
      
- template: build-package.netfx.yaml@templates
  parameters:
    packagePath: Audacia.Seed/Audacia.EntityFramework6.csproj