name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: pipelines/build/nuget-package.job.yaml@templates
  
- stage:
  displayName: Release
  jobs:
  - template: pipelines/release/internal-nuget-package.job.yaml@templates