name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: jobs/build/netcore/package.yaml@templates
  
- stage:
  displayName: Release
  jobs:
  - template: jobs/release/netcore/internal-package.yaml@templates