name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

stages:
- stage:
  displayName: Build
  jobs:
  
  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.Seed
      projects: Audacia.Seed/Audacia.Seed.csproj
  
  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.Seed.AutoFixture
      projects: Audacia.Seed.AutoFixture/Audacia.Seed.AutoFixture.csproj
  
  - template: jobs/build/netcore/package.yaml@templates
    parameters:
      displayName: Audacia.Seed.EntityFrameworkCore
      projects: Audacia.Seed.EntityFrameworkCore/Audacia.Seed.EntityFrameworkCore.csproj
  
  - job:
    displayName: Audacia.Seed.EntityFramework6
    steps:      
    - template: steps/build/netfx/package.yaml@templates
      parameters:
        projects: Audacia.Seed.EntityFramework6/Audacia.Seed.EntityFramework6.csproj

- stage:
  displayName: Release
  jobs:
  - template: jobs/release/netcore/internal-package.yaml@templates