name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: [master]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }

jobs:

- job:
  displayName: Audacia.Seed
  steps:
  - template: build-package.netcore.yaml@templates
    parameters:
      projects: Audacia.Seed/Audacia.Seed.csproj

- job:
  displayName: Audacia.Seed.AutoFixture
  steps:
  - template: build-package.netcore.yaml@templates
    parameters:
      projects: Audacia.Seed.AutoFixture/Audacia.Seed.AutoFixture.csproj

- job:
  displayName: Audacia.Seed.EntityFrameworkCore
  steps:
  - template: build-package.netcore.yaml@templates
    parameters:
      projects: Audacia.Seed.EntityFrameworkCore/Audacia.Seed.EntityFrameworkCore.csproj
        
- job:
  displayName: .NET Framework
  steps:      
  - template: build-package.netfx.yaml@templates
    parameters:
      projects: Audacia.Seed.EntityFramework6/Audacia.Seed.EntityFramework6.csproj